steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/blazevortex-image:$SHORT_SHA'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/blazevortex-image:$SHORT_SHA'

timeout: '1200s'  # 20 mins