name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  protect-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 20  # should be enough...

      - name: Detect and revert unauthorized direct pushes
        run: |
          git fetch origin main

          # Find the first merge commit
          MERGE_COMMIT=$(git log --pretty=format:"%H %s" | grep -m 1 "^.* Merge pull request" | awk '{print $1}')

          if [ -z "$MERGE_COMMIT" ]; then
            echo "❌ No valid merge commit found! Cannot revert safely."
            exit 1
          fi

          echo "✅ Last good merge commit: $MERGE_COMMIT"

          # Reset main branch to last good PR merge
          git reset --hard "$MERGE_COMMIT"
          git push origin main --force

          echo "🔁 Successfully reverted unauthorized direct commits."
