name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  check-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20  # Should be enough...

      - name: Check commit and revert if necessary
        run: |
          echo "🔍 Checking last commit..."
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "🔹 Commit message: $COMMIT_MESSAGE"

          if [[ "$COMMIT_MESSAGE" != Merge\ pull\ request* ]]; then
            echo "❌ Unauthorized direct push detected! Reverting..."
            
            git fetch origin main
            LAST_GOOD_COMMIT=$(git rev-parse HEAD~1)
            git reset --hard $LAST_GOOD_COMMIT
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main --force
            exit 1
          else
            echo "✅ PR merge detected. No action needed."
          fi
