name: Deploy on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            pkill -f "ts-node ./src/index.ts" || true
            cd ./BlazeVortex
            git pull
            npm install
            timestamp=$(TZ=America/Chicago date +"[CST %m/%d %I:%M %p]")
            echo "$timestamp Github BlazeVortex start initiated 🔥 ✅ 🚀"
            echo "$timestamp Github BlazeVortex start initiated 🔥 ✅ 🚀" >> out.log
            nohup bash -c 'npm run start-ubuntu 2>&1 | awk '\''{ \
              cstcmd="TZ=America/Chicago date +\"[CST %m/%d %I:%M %p]\""; \
              pktcmd="TZ=Asia/Karachi date +\"[PKT %I:%M %p]\""; \
              cstcmd | getline cst; close(cstcmd); \
              pktcmd | getline pkt; close(pktcmd); \
              print cst, pkt, $0; fflush(); \
            }'\'' >> out.log' </dev/null >/dev/null 2>&1 &
          EOF

