name: Deploy on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to server via SSH with password
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          pkill -f "ts-node ./src/index.ts" || true
          cd ./BlazeVortex
          git pull
          npm install
          timestamp=$(date +"[%I:%M:%S %p %Z]")
          echo "$timestamp BlazeVortex start initiated at $timestamp 🔥 ✅ 🚀"
          echo "$timestamp BlazeVortex start initiated at $timestamp 🔥 ✅ 🚀" >> out.log
          nohup bash -c 'npm run start-ubuntu 2>&1 | awk '\''{ cstcmd="TZ=America/Chicago date +\"[CST: %Y-%m-%d %I:%M:%S %p]\""; utc="TZ=UTC date +\"[UTC: %Y-%m-%d %I:%M:%S %p]\"";  pkt="TZ=Asia/Karachi date +\"[PKT: %Y-%m-%d %I:%M:%S %p]\""; cstcmd | getline cst; close(cstcmd); utc | getline u; close(utc); pkt | getline p; close(pkt); print cst, u, p, $0; fflush(); }'\'' >> out.log' </dev/null >/dev/null 2>&1 &
        EOF
